import React, { useState } from "react";
import { useForm } from "react-hook-form";
import ReCAPTCHA from "react-google-recaptcha";
import emailjs from "emailjs-com";
import licImg from "../../../assets/img/id.jpg";

export default function LicenceForm() {
  const { register, control, handleSubmit, watch } = useForm();
  const [captcha, setCaptcha] = useState(null);

  const sendEmail = (formData) => {
    console.log(formData);

    // if (captcha) {

    // emailjs
    //   .send("service_ldxbl2a", "template_4hokf8f", formData, "eIgtXFdKWTCe8NiPY")
    //   .then(
    //     (result) => {
    //       console.log(result.text);
    //     },
    //     (error) => {
    //       console.log(error.text);
    //     }
    //   );

    // }
  };

  function onChange(value) {
    setCaptcha(true);
  }

  return (
    <div>
      <div className="formLicenceLabel">
        Do not close this window until your process is complete!
      </div>

      <div className="formLicence">
        <h2 className="formLicence__title">
          Thank you for purchasing <br /> OTM Software{" "}
        </h2>

        <h4 className="formLicence__subTitle">
          You are only a few steps away from having your OTM software
        </h4>

        <p className="formLicence__numeration">
          1. Get the ID machine of your Ninjatrader 8:
        </p>

        <div className="formLicence__idImage">
          <img src={licImg}></img>
        </div>

        <p className="formLicence__caption">
          {" "}
          The Machine ID code is generated by NinjaTrader based on the main
          hardware and software system.
        </p>

        <p className="formLicence__numeration  formLicence__numeration--end">
          2. Send us the machine ID and your data in the following form:
        </p>

        <form onSubmit={handleSubmit(sendEmail)}>
          <div className="formLicence__campo">
            <h3>Name:</h3>
            <input {...register("name")} placeholder="Jhon Due" type="text" />
          </div>

          <div className="formLicence__campo">
            <h3>ID machine:</h3>
            <input {...register("id")} placeholder="AAAAAAAAAAA" type="text" />
          </div>

          <div className="formLicence__campo">
            <h3>Email:</h3>
            <input {...register("email")} placeholder="sample@mail.com" type="text" />
          </div>

          <div className="formLicence__campo">
            <h3>Message:</h3>
            <textarea {...register("message")} placeholder="..." />
          </div>

          <div className="formLicence__recaptcha">
            <ReCAPTCHA
              sitekey="6Ldy4bUiAAAAAH9ZiMjWguQIIigWl8LafZI38GKm"
              onChange={onChange}
              size={window.innerWidth < 640 ? "compact" : "normal"}
              theme="dark"
            />
          </div>

          <div className="formLicence__boton">
            <button type="submit">Submit</button>
          </div>
        </form>


        <p className="formLicence__clarif">
        • You will receive your software in your email within 1 business day (8 to 5 PM GMT-4).
        </p>      

        <p className="formLicence__clarif">
        • If you have any questions please do not hesitate to contact us:
        </p>  

        <p className="formLicence__clarif">
        » info@otmtrading.com <br/> » WhatsApp support (+57 311 3006826)
        </p>   

      </div>
    </div>
  );
}
